// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyUser.Models;

#nullable disable

namespace MyUser.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20231209151518_DBCreated")]
    partial class DBCreated
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyUser.Models.Backpack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Backpacks", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a70e6a2c-bf0f-4b1b-92f7-b210c3db8ae7"),
                            Name = "First",
                            UserId = new Guid("52d8073d-2532-4916-8580-760780f023a1")
                        },
                        new
                        {
                            Id = new Guid("c0050d51-3942-4603-bb3e-479e38d1cf0f"),
                            Name = "Second",
                            UserId = new Guid("52d8073d-2532-4916-8580-760780f023a1")
                        });
                });

            modelBuilder.Entity("MyUser.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(max)")
                        .HasComputedColumnSql("[FirstName] + ' ' + [LastName]", true);

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("52d8073d-2532-4916-8580-760780f023a1"),
                            Age = 0,
                            FirstName = "Jahonger",
                            LastName = "Ahmedov"
                        },
                        new
                        {
                            Id = new Guid("705ff84b-aa48-4c99-8e12-ad4dee113fa8"),
                            Age = 0,
                            FirstName = "Jake",
                            LastName = "Esh"
                        },
                        new
                        {
                            Id = new Guid("d1afe4f2-4a5a-47ad-b1fa-f8cafb4aade5"),
                            Age = 0,
                            FirstName = "Rasul",
                            LastName = "Azimov"
                        });
                });

            modelBuilder.Entity("MyUser.Models.Backpack", b =>
                {
                    b.HasOne("MyUser.Models.User", "User")
                        .WithMany("Backpacks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyUser.Models.User", b =>
                {
                    b.Navigation("Backpacks");
                });
#pragma warning restore 612, 618
        }
    }
}
