// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyUser.Models;

#nullable disable

namespace MyUser.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20231211054134_UsernameAndPasswordAdded")]
    partial class UsernameAndPasswordAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyUser.Models.Backpack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Backpacks", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("763b50f2-b262-4be1-9986-c88f5495cfca"),
                            Name = "First",
                            UserId = new Guid("3b87b87c-808b-4bc7-a3b6-3e98bfba9e2a")
                        },
                        new
                        {
                            Id = new Guid("5593aafe-f4bd-40e0-a5ea-5a85eba786ef"),
                            Name = "Second",
                            UserId = new Guid("3b87b87c-808b-4bc7-a3b6-3e98bfba9e2a")
                        });
                });

            modelBuilder.Entity("MyUser.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(max)")
                        .HasComputedColumnSql("[FirstName] + ' ' + [LastName]", true);

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("3b87b87c-808b-4bc7-a3b6-3e98bfba9e2a"),
                            Age = 0,
                            FirstName = "Jahonger",
                            LastName = "Ahmedov",
                            Password = "User11",
                            Username = "User1"
                        },
                        new
                        {
                            Id = new Guid("340d235d-a94d-41e7-9af4-05aae2df2120"),
                            Age = 0,
                            FirstName = "Jake",
                            LastName = "Esh",
                            Password = "User22",
                            Username = "User2"
                        },
                        new
                        {
                            Id = new Guid("dabc6326-02f5-4f10-95f3-3995da0ca8f9"),
                            Age = 0,
                            FirstName = "Rasul",
                            LastName = "Azimov",
                            Password = "User33",
                            Username = "User3"
                        });
                });

            modelBuilder.Entity("MyUser.Models.Backpack", b =>
                {
                    b.HasOne("MyUser.Models.User", "User")
                        .WithMany("Backpacks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyUser.Models.User", b =>
                {
                    b.Navigation("Backpacks");
                });
#pragma warning restore 612, 618
        }
    }
}
